// <auto-generated />
using Bioverse.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace bioverse.Migrations
{
    [DbContext(typeof(BioverseContext))]
    [Migration("20210726191036_AddIPRange")]
    partial class AddIPRange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Bioverse.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_family");

                    b.ToTable("family");
                });

            modelBuilder.Entity("Bioverse.Models.FirewallRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.HasKey("Id")
                        .HasName("pk_firewall_rule");

                    b.ToTable("firewall_rule");
                });

            modelBuilder.Entity("Bioverse.Models.IPRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FirewallRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("firewall_rule_id");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("range");

                    b.HasKey("Id")
                        .HasName("pk_ip_range");

                    b.HasIndex("FirewallRuleId")
                        .HasDatabaseName("ix_ip_range_firewall_rule_id");

                    b.ToTable("ip_range");
                });

            modelBuilder.Entity("Bioverse.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("family_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_species_family_id");

                    b.ToTable("species");
                });

            modelBuilder.Entity("Bioverse.Models.IPRange", b =>
                {
                    b.HasOne("Bioverse.Models.FirewallRule", "FirewallRule")
                        .WithMany("IPRange")
                        .HasForeignKey("FirewallRuleId")
                        .HasConstraintName("fk_ip_range_firewall_rule_firewall_rule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirewallRule");
                });

            modelBuilder.Entity("Bioverse.Models.Species", b =>
                {
                    b.HasOne("Bioverse.Models.Family", "Family")
                        .WithMany("Species")
                        .HasForeignKey("FamilyId")
                        .HasConstraintName("fk_species_family_family_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Bioverse.Models.Family", b =>
                {
                    b.Navigation("Species");
                });

            modelBuilder.Entity("Bioverse.Models.FirewallRule", b =>
                {
                    b.Navigation("IPRange");
                });
#pragma warning restore 612, 618
        }
    }
}
